#
# Makefile to support asd boards
#

# MBX

obj-$(CONFIG_MACH_MESON6_G18_ATV102S)		+= board-m6g18-atv102s.o
obj-$(CONFIG_MACH_MESON6_G18_DBXM6)		+= board-m6g18-dbxm6.o
obj-$(CONFIG_MACH_MESON6_G18_DBXMX)		+= board-m6g18-dbxmx.o

# Tablet

obj-$(CONFIG_MACH_MESON6_PMP5670C)		+= board-PMP5670C.o
obj-$(CONFIG_MACH_MESON6_PMP5670C)		+= board-PMP5670C-panel.o
